version: "3.8"

services:
  nginx:
    image: nginx:alpine
    ports:
      - "81:81"  # 호스트의 81 포트를 컨테이너의 80 포트로 매핑
      - "442:443" # HTTPS 포트
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    expose:
      - "3000"  # 실제 내부 포트
    ports:
      - "3001:3000"  # 호스트 3001 포트를 컨테이너의 3000 포트로 매핑
    environment:
      - NUXT_PORT=3000  # Nuxt 앱이 3000 포트에서 실행되도록 설정
      - NUXT_HOST=0.0.0.0  # 모든 IP에서 접근 가능하도록 설정
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - "8000"
    ports:
     - "8000:8000"
    env_file:
      - ./backend/.env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge